Inner-Worlds/inner_worlds_be

app/models/dream.rb
app/models/dream_emotion.rb
app/models/dream_tag.rb
app/models/emotion.rb
app/models/tag.rb
app/models/user.rb
db/migrate/20230512211617_create_users.rb
db/migrate/20230512212114_create_dreams.rb
db/migrate/20230512212152_create_tags.rb
db/migrate/20230512212211_create_emotions.rb
db/migrate/20230512212307_create_dream_tags.rb
db/migrate/20230512212336_create_dream_emotions.rb
db/schema.rb
spec/factories/dream_emotions.rb
spec/factories/dream_tags.rb
spec/factories/dreams.rb
spec/factories/emotions.rb
spec/factories/tags.rb
spec/factories/users.rb
spec/models/dream_emotion_spec.rb
spec/models/dream_spec.rb
spec/models/dream_tag_spec.rb
spec/models/emotion_spec.rb
spec/models/tag_spec.rb
spec/models/user_spec.rb

Description of Changes: Make Database
Checks
Tests Written ? [n/a]
Tests Passing [n/a]
Code Will Run Locally on Postman [n/a]
Closes #10 
Co-Authors: Sam Walker 
Bobby Luly
Weston Sandfort
Kassandra Leyba

db: create database

---

Gemfile
Gemfile.lock
db/seeds.rb
spec/factories/dreams.rb
spec/rails_helper.rb

Description of Changes: fix seed data and factories
Checks
Tests Written ? [n/a]
Tests Passing [n/a]
Code Will Run Locally on Postman [n/a]
Closes #10

Graph ql setup

---

app/graphql/mutations/delete_dream.rb
app/graphql/types/mutation_type.rb
app/models/dream.rb
spec/requests/mutations/dreams/delete_dream_spec.rb

- Adds functionality to delete a User's dream
Checks
Closes #7

BE | Create `Mutations::DeleteDream`

---

Gemfile

Description of Changes: read commit

move faker out of development group in gemfile

---

db/schema.rb
db/seeds.rb

Checks
Code Will Run Locally on Postman [n/a]

make more seed data, and delete all tables when reseeding

---

Gemfile
Gemfile.lock
config/application.rb

Description of Changes: Sets up cors 
Checks
Tests Written ? [n/a]
Closes #

set up cors

---

db/seeds.rb

Description of Changes:  fix seeds delete order

fix seeds delete order

---

app/graphql/inner_worlds_be_schema.rb
app/graphql/types/query_type.rb
spec/requests/queries/users/get_user_spec.rb

Description of Changes: Add error handling for querying a user
Checks
Closes #11 

feat: add error handling for quering a user

---

app/graphql/mutations/delete_dream_emotion.rb
app/graphql/mutations/delete_dream_tag.rb
app/graphql/types/mutation_type.rb
spec/requests/mutations/dreams/emotions/delete_dream_emotions_spec.rb
spec/requests/mutations/dreams/tags/delete_dream_tag_spec.rb

Description of Changes: Deletion of dream tag and dream emotion
Checks
Closes #14 #44 

Delete dream emotion

---

db/seeds.rb

Description of Changes: This perhaps will fix the DB issue we are having, and hopefully  PKs will start at 1 going forward.

truncate the database when running rails db seed

---

app/graphql/types/dream_type.rb
db/seeds.rb
spec/requests/mutations/dreams/create_user_dream_spec.rb

Description of Changes: Formats the dates for the front end. 
Checks
Tests Written ? [n/a]--Updated a test that had the old Dream Date formatting
Closes #50 

Weston dates

---

app/graphql/types/user_type.rb
app/models/user.rb
spec/models/user_spec.rb
spec/requests/queries/users/get_user_spec.rb

Description of Changes: When the front end requests the dreams for a user, they are now sorted by the dream's date.
Checks
Closes #58 

Dream sort date

---

app/graphql/mutations/update_dream.rb
spec/requests/mutations/dreams/update_dream_spec.rb

Description of Changes: Changes forward slashes to hyphens for updating a dream date string. 
Checks
Tests Written ? [x] Fixed a test

fix: update dream formatting issue

---

app/models/user.rb
spec/models/user_spec.rb
spec/requests/queries/users/stat_spec.rb

- Create `User#top_5_tags` instance method
- create Model and Request tests
Checks
Closes #

BE | Create `User#top_5_tags` instance method for a User's stats

---

app/models/user.rb
spec/models/user_spec.rb
spec/requests/queries/users/stat_spec.rb

Description of Changes: Create top_5_emotions model method fully tested with model test and request test
Checks
Closes #66 

Top 5 emotions

---

README.md

- Create initial `ReadME`
- Update Schema, Project Description,  Logo, Inner Worlds team/contact info
Checks
Closes #

BlE | Create initial `ReadME`

---

app/graphql/mutations/update_dream.rb

Description of Changes: Allows the front end to send 2 different date formats for updating a dream
Checks
Tests Written ? [TODO]

bug fix: dates update regardless of the format

---

app/models/user.rb
spec/models/user_spec.rb

Description of Changes: User methods for dreams_this_week stat and dreams_this_month stat and associated tests added.
Checks
Tests Written ? [X]
Tests Passing [X]
Code Will Run Locally on Postman []**postman limit issue
Closes #21

Dreams in a week and dreams in a month stats

---

Gemfile
Gemfile.lock
app/models/user.rb
spec/models/user_spec.rb
spec/requests/mutations/dreams/create_user_dream_spec.rb
spec/requests/queries/users/stat_spec.rb

add current streak and longest streak to stats

---

README.md

Updated the Readme
Checks
Tests Passing []
Closes #

Bl read me update

---

.env
db/seeds.rb

Added two users to the top of the seed file with standardized, non faker data for the FE
Checks
Closes #

Add seed users for FE

---

spec/requests/mutations/dreams/update_dream_spec.rb

Description of Changes: Test added for update dream date formatting.
Checks
Tests Written ? [X]
Tests Passing [X]
Closes #
Co-Authors: Weston Sandfort <sandfortw@gmail.com>

Add test to update dream to fully test date formatting functionality

---

app/models/user.rb
spec/models/user_spec.rb

Description of Changes: This changes all time average lucidity to weekly average lucidity
Checks
Closes #

Update average lucidity to weekly average lucidity

---

spec/models/user_spec.rb

Reverts Inner-Worlds/inner_worlds_be#80

Revert "Lucidity"

---

Gemfile
Gemfile.lock
app/services/topic_service.rb
spec/cassettes/services/get_bad_topics.yml
spec/models/user_spec.rb
spec/requests/queries/users/stat_spec.rb
spec/services/topic_service_spec.rb

Description of Changes: Fixes bug where test was failing to stub time. 
Checks
Tests Written ? [n/a]
Code Will Run Locally on Postman [n/a]

Create dream edge case

---

README.md
db/schema.rb
db/seeds.rb
spec/requests/queries/users/stat_spec.rb

- Change seed data to make dream_dates for first 2 users dynamic. Change faker users from 100 to 10
- Add all GraphQL endpoints, successful and unsuccessful in the ReadME
Checks
Closes #

BE | Update ReadME, change some seed data 

---

spec/models/user_spec.rb
spec/requests/mutations/dreams/update_dream_spec.rb

Description of Changes: Added timecop to weekly dreams count test as well as monthly.
Checks
Tests Written ? [X]
Tests Passing [X]
Closes #

slight edit to user spec testing

---

README.md
spec/requests/queries/users/stat_spec.rb

- Add links to the front end repo for the logo and a couple other spots
- Add more built with badges
Checks
Closes #

BE | Add last second ReadME Updates

---

README.md
app/services/topic_service.rb

There was a small error in the readme that had the wrong key for the environmental variable where the user puts their API key. Also, I changed an unnecessary environmental variable in the code to plaintext. 
Checks
Closes #

Readme fix

---

.gitignore

This adds a few files required for deploying to elastic beanstalk to gitignore. This affects nothing, effectively.

add elastic beanstalk files to gitignore

---

.platform/hooks/nginx/conf.d/elasticbeanstalk/cable.conf
.platform/hooks/nginx/conf.d/elasticbeanstalk/webpack.conf

Troubleshooting deployment by trying the nginx code I thought was useless.

nginx config
